name: ls_cst
margin: 20.0
t_logb: 10.0
w_logb: 0.1
schedule: ""
max_t: 100.0
step_size: 100
mu: 0

object:
  _target_: calibrate.losses.LabelSmoothConstrainedLoss
  margin: ${loss.margin}
  t_logb: ${loss.t_logb}
  w_logb: ${loss.w_logb}
  mu: ${loss.mu}
  schedule: ${loss.schedule}
  max_t: ${loss.max_t}
  step_size: ${loss.step_size}